---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        exclude: cspell.json
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
        exclude: mkdocs.yml
        args: [--allow-multiple-documents]
      - id: requirements-txt-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict -f parsable
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.3
    hooks:
      # Spell check changed files
      - id: cspell
      # Spell check the commit message
      - id: cspell
        name: check commit message spelling
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]
        always_run: true
  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.15.0
    hooks:
      - id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl
        language: ruby
        files: \.(md|mdown|markdown)$
  - repo: local
    hooks:
      - id: go-verify
        name: go-verify
        language: system
        entry: ./.pre-commit/go-mod-hook
        require_serial: true
      - id: gci
        name: gci
        language: system
        entry: ./.pre-commit/gci-hook
        require_serial: true
